name: "build"
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install cross-compilation deps
        run: |
          sudo apt update
          sudo apt install -q -y \
            binfmt-support \
            gcc-aarch64-linux-gnu \
            qemu-system-aarch64 \
            qemu-user-static
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-22.05
          extra_nix_config: |
            extra-platforms = aarch64-linux
            max-jobs = auto
            cores = 0
            system-features = big-parallel kvm
            experimental-features = nix-command flakes
      - run: |
          nix show-config | grep -vi -e keys -e token
          nix build --print-build-logs --show-trace
          nix show-derivation ./result

      # Workaround for https://github.com/actions/upload-artifact/issues/92
      - run: echo "UPLOAD_PATH=$(readlink -f result)/iso" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: rescue
          path: ${{ env.UPLOAD_PATH }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: ${{ env.UPLOAD_PATH }}/*
